Make typechecking work with "moduleResolution": "node16" (Fixes #6)
syntax-tree/mdast-util-directive pull request #7
Opened 2023-01-26 21:35 UTC by jameshfisher

### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

Fix issue described in https://github.com/syntax-tree/mdast-util-directive/issues/6

2023-01-26 21:41 UTC, ChristianMurphy requested changes
Thanks @jameshfisher!
`node16` module resolution is something making its way through the ecosystem, but hasn't reached here yet.
Thanks for looking into it.

A couple items to get it across the finish line.
1. Could you update the ts config of this project to use node16 resolution (using the same config options elsewhere https://github.com/syntax-tree/mdast-util-assert/blob/8958dff406cb658abc4189568ed7af2c56d9320c/tsconfig.json)
2. Could you look into the type error currently breaking CI? (which may require going to some of this project's dependencies and updating them to support `node16` mode as well)

2023-01-27 12:34 UTC, wooorm commented
Yup, you should be able to port this commit: https://github.com/syntax-tree/mdast-util-assert/commit/8958dff406cb658abc4189568ed7af2c56d9320c. And things will work :)

2023-01-28 18:23 UTC, jameshfisher commented
@wooorm I've ported that commit, updated some dependencies, and tried to resolve some broken references in imports. It still has lots of type-checking errors though, and I don't know how to resolve them.

(It doesn't help that my laptop explodes and takes 15+ seconds for types to update when making any single-character changes in VS Code. This seems to be associated with instances of `visit` causing some perverse worst-case in type-checking. Any advice on this weird problem appreciated!)

2023-01-28 18:27 UTC, remcohaszing requested changes
Thank you! Just 2 small suggestions

2023-01-28 18:27 UTC, remcohaszing commented on index.js
> + * @typedef {import('mdast-util-to-markdown/index.js').Context} Context
```suggestion
 * @typedef {import('mdast-util-to-markdown').Context} Context
```

2023-01-28 18:27 UTC, remcohaszing commented on index.js
> +  /** @type {import('unist-util-visit-parents/complex-types.js').BuildVisitor<Root, Directive>} */
```suggestion
  /** @type {import('unist-util-visit-parents').BuildVisitor<Root, Directive>} */
```

2023-01-29 17:38 UTC, wooorm approved these changes

2023-01-29 17:39 UTC, merged

2023-01-29 17:39 UTC, wooorm commented
Thanks!

2023-01-30 09:22 UTC, wooorm commented
Released in 2.2.3!